<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/Resumen_181619.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Resumen

Monica Hernandez Quiroz - 181619

In [2]:

!pip install sentence-splitter

Requirement already satisfied: sentence-splitter in /usr/local/lib/python3.13/dist-packages (1.4)
Requirement already satisfied: regex>=2017.12.12 in /usr/local/lib/python3.13/dist-packages (from sentence-splitter) (2025.11.3)

In [3]:
import os
import nltk
import random
import collections
from sentence_splitter import SentenceSplitter

In [4]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

## Lectura, segmentación y normalización del libro

In [5]:
#Tokenizador
def tokenizar(libro):
    puntuacion = r'!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~¿¡—–'

    # Normalizar
    libro = libro.lower()

    # Tokenizar
    tokens = nltk.word_tokenize(libro, "spanish")

    # Quitar puntuación de los extremos
    for i, token in enumerate(tokens):
        tokens[i] = token.strip(puntuacion)

    # Volver a formar texto
    texto = " ".join(tokens)

    # Tokenizar nuevamente
    tokens = nltk.word_tokenize(libro, "spanish")

    return tokens

In [6]:
def segmentar_oraciones_tokens(texto):
    splitter = SentenceSplitter(language = 'es')
    texto = texto.replace('\n', ' ').replace('\r', '')
    oraciones = splitter.split(texto)
    oraciones_tokenizadas = []
    for oracion in oraciones:
        if not oracion: continue
        tokens = tokenizar(oracion)
        oraciones_tokenizadas.append(tokens)
    for i, oracion in enumerate(oraciones_tokenizadas):
        oraciones_tokenizadas [i] = [""] + oracion + [""]
    return oraciones_tokenizadas

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
ruta = '/content/drive/MyDrive/IA/turing.txt'

with open(ruta, 'r', encoding='utf-8') as archivo:
    libro = archivo.read()

print(libro)

El matemático inglés Alan Turing fue uno de los pioneros más importantes en el delineamiento de lo que más tarde se convertiría en la teoría de la computación. El misterio fue un común denominador a lo largo de su vida, entre otras cosas por su participación en el servicio británico de inteligencia durante la Segunda Guerra Mundial y por sus mal vistas inclinaciones sexuales. Su vida, llena de soledad y tropiezos, fue duramente juzgada al exponer públicamente su homosexualidad en los años cincuenta, pero ni la depresión ni el cruel repudio de la sociedad -a la que su trabajo contribuyó a liberar del yugo alemán- parecen justificar su trágico suicidio, cometido cuando se encontraba en el clímax de su productividad científica.

Sus calificaciones en matemáticas y ciencias eran aceptables, pero los maestros se quejaban de lo sucio de su trabajo. Su madre se encontraba sumamente mortificada porque pensaba que Alan vería truncadas sus aspiraciones científicas por su mal desempeño en la escuela. Con esas calificaciones parecía improbable que Alan pudiera siquiera aspirar a ingresar a la universidad. El director de la escuela llegó a decir si Alan Turing deseaba ser científico estaba desperdiciando su tiempo en una escuela pública. Esas palabras fueron casi ciertas, pues Turing hubo de sufrir mucho durante su estancia en esa institución, en la que los anticuados métodos de enseñanza británicos afortunadamente no lograron apaciguar su curiosidad por la ciencia. Si su madre y sus profesores hubieran sabido en ese entonces que este joven indisciplinado estaba destinado a convertirse en un matemático connotado y que un día su nombre sería pronunciado con respeto por los teóricos de la computación más importantes del mundo, tal vez le habrían tenido un poco más de paciencia.

Alan Turing fue el segundo y último hijo de Julius Turing y Ethel Sara Stone. El inusual apellido Turing lo colocaba en el árbol genealógico de una familia que, aunque no era rica, pertenecía a la clase media alta inglesa. Su padre ingresó al servicio civil de la India y durante su estancia en ese país conoció a la que más tarde sería su esposa. Ethel era la hija del ingeniero en jefe de los ferrocarriles de Madras (en la India) y provenía de una familia anglo-irlandesa de un estatus socioeconómico similar al de Julius.

 Aunque fue concebido en la India, probablemente en el pueblo de Chatrapur, Alan Turing nació en Warrington Lodge, en Londres, Inglaterra, el 23 de junio de 1912. Alan Turing y su hermano mayor John pasaron una infancia alejados de sus padres, siempre bajo el cuidado de terceras personas en diversos hogares ingleses, hasta que su padre se retiró del servicio en 1926.

Se dice que la inteligencia de Alan Turing se manifestó a temprana edad, puues a los 3 años parecía mostrar una inusual capacidad para recordar nuevas palabras. Al parecer, su gusto por la educación autodidacta también se manifestó en su niñez porque su madre cuenta que Alan estaba aprendiendo muy lentamente a leer, hasta que éste encontró un libro fácil de seguir y se enseñó a sí mismo. Asimismo, su inquietud por entender los fenómenos de la naturaleza lo llevó a montar un laboratorio rudimentario de química en el sótano de su casa, cuando contaba con solo ocho años de edad.

De niño, Alan quería ser médico, por lo que su familia veía con buenos ojos su temprano interés en la química. Además, buscando que el pequeño recibiera una buena educación básica, sus padres lo enviaron en el verano de 1918 a una escuela privada para niños llamada Saint Michael’s para que aprendiera latín. Después de un tiempo su mamá lo sacó de la escuela, porque advirtió que Alan no estaba aprendiendo mucho, ya que llegó a los nueve años de edad sin saber dividir correctamente y sin haber alcanzado un nivel aceptable de latín. En 1922 Alan ingresó a la escuela preparatoria Hazlehurst, que era donde estudiaba su hermano.

Fue en Hazlehurst donde Alan se interesó por primera vez en el ajedrez, y fue ahí también donde su interés por la ciencia -sobre todo la química y las matemáticas- fue creciendo cada vez más, aunque gran parte de sus estudios tuvo que efectuarlos de manera autodidacta, debido al arcaico sistema de enseñanza que reinaba en la Inglaterra de esos días.

A pesar de su mal desempeño en la escuela, Alan sorprendió agradablemente a su familia cuando aprobó el examen común de admisión a escuelas públicas en 1925. Sin embargo, como su madre deseaba enviar a Alan a una escuela donde pudiera entender su extraña manera de ser y su extraordinario sentido de independencia, hubo que esperar hasta 1926 para ingresar a la escuela Sherborne, cuando contaba con 13 años de edad.

A los 14 años ya era capaz de comprender cuestiones relativamente avanzadas de cálculo, pese a que no había estudiado el tema en la escuela. Asimismo, se dice que tenía una increíble capacidad para realizar cálculos mentales. Fue en esta época también en la que empezó a desarrollar una afición hacia el atletismo que le acompañaría toda la vida.

Pese a su mal desempeño en materias no relacionadas con las ciencias. Turing logró sobrevivir en Sherborne y continuó estudiando matemáticas por su cuenta. En 1928 se interesó en la teoría general de la relatividad, de Albert Einstein, y aunque se dice que sus notas privadas sobre la materia bien podrían atribuirse a un estudiante de posgrado, casi se le impidió tomar los exámenes para obtener el certificado de educación media.

Durante su estancia en Sherborne, Turing desarrolló el hábito de no prestar atención a sus clases sino hasta el final del semestre, cuando se esmeraba y dejaba asombrados a todos al obtener calificaciones suficientemente buenas para aprobar sus cursos. Un profesor de latín, llegó a decirle al intrépido Alan que donaría un billón de libras a cualquier institución de beneficencia que Turing eligiera si este lograba aprobar su curso. A pesar del mal presagio, Alan se las ingenió para aprobar latín, aunque su profesor no honró la apuesta.

Fue en estos días cuando Turing conoció al joven Christopher Morcom, un estudiante muy brillante que le sirvió de compañero intelectual durante una época de intensa curiosidad científica para Alan. Morcón provenía de una familia rica con fuertes bases científicas y artísticas. Tras conocerlo, Turing se sintió inmediatamente atraído por el enorme talento y las sagaz inteligencia de Morcom y pronto se volvieron muy buenos amigos. Incluso a veces les tocó compartir clases, a pesar de que Christopher era un año mayor que Alan. Juntos desarrollaron experimentos de química, resolvieron problemas de matemáticas, localizaron estrellas y cometas en el firmamento y conversaron durante interminables horas acerca de las inagotables ideas y preguntas científicas que intrigaban a los jóvenes prospectos.

Aunque igualmente brillante que Alan, Christopher se distinguía de Turing por ser un estudiante modelo que sabía obedecer las rígidas reglas que regían en las escuelas inglesas de educación media de la época. Además, poseía aptitudes que estaban mucho más allá de la capacidad de Turing. Tal vez por ello Morcom se volvió el primer héroe de la adolescencia de Turing y según Hodges, su primer gran amor platónico.

En 1929 Morcom presentó los exámenes para ingresar al prestigioso Trinity College de la Universidad de Cambridge, y obtuvo una beca -al igual que lo había hecho su hermano Rupert unos años antes que él-. Turing tuvo la osadía de imitar a Morcom, a pesar de contar con solo 17 años de edad y, como era de esperarse, fracasó en su intento.

Lo que Turing lamentó más de este tropiezo no fue tanto el no haber obtenido la beca, sino el pensar que se tendría que separar de Christopher durante al menos un año. Lo que Alan no sabía era que el destino estaba a punto de jugarle una mala pasada que los separaría permanentemente de la única persona que realmente comprendía su peculiar interés por la ciencia.

Christopher Morcom murió el 13 de febrero de 1930, después de 6 días de intenso dolor. Aunque Turing atribuyó su muerte a un envenenamiento envenenamiento con vanadio, la realidad es que Morcom había contraído tuberculosis bovina en la infancia por beber leche de vaca infectada y eso lo había hecho ser siempre una persona muy enfermiza. Su mal se agudizó tras una operación que se efectuó en 1927 y todos los esfuerzos de los médicos por salvarlo fueron inútiles.

Su muerte dejó huella profunda en Turín, quien juró completar la prometedora carrera científica que Morcom había apenas comenzado. A partir de ese momento Alan inició una correspondencia frecuente con la mamá de Christopher y sus intereses se tornaron hacia los misterios que rodean el encapsulamiento de la mente en la materia. Con el firme propósito de develar los secretos de la muerte con ayuda de la ciencia, Turing comenzó a estudiar física cuántica.

En su segundo intento por obtener una beca en Cambridge, Turing finalmente logro ser aceptado en el King’s College, que fue su segunda opción en el examen.

Esto decepcionó un poco Alan, que lamentó no haber podido seguir fielmente los pasos de Christopher, pero fue motivo de celebración para la familia Turín, que pensó que después de todo su hijo obtendría la buena educación que todos buscaban.

En 1932 Alan comenzó a estudiar el entonces reciente trabajo de von Newman en mecánica cuántica, lo cual le permitió canalizar sus dudas espirituales por la vía de la rigurosidad científica. Al mismo tiempo, el ambiente más liberal del King’s College le hizo sentirse mucho más relajado que en Sherborne, y la homosexualidad se volvió un rasgo distintivo de su personalidad. En esa época hizo amistad con un joven estudiante de matemáticas llamado James Atkins, quien se volvería más tarde su amante.

Pese a que los círculos más frecuentados por los homosexuales en King’s College eran los literarios, Turing prefería los deportes y era frecuente que practicara remo, carreras a campo traviesa y que paseara en un pequeño velero. También aprendió a tocar el violín, pero nunca se volvió diestro con el instrumento. Tal vez debido a su constante oposición a los sistemas rígidos como los que había experimentado en su adolescencia. Turing se unió al movimiento antibélico que pululaba en el Cambridge de los años treinta. Sus ideas de esa época estaban a favor de la izquierda, aunque nunca llegó a participar directamente en ningún movimiento político importante.

Las cosas empezaron a ir bien para Turing, pues se graduó de la licenciatura en matemáticas con honores en 1934. Su redescubrimiento del teorema del límite central le hizo acreedor a una beca Harold Fry del King’s College, que le permitía ser investigador de tiempo completo durante tres años, con posibilidad de renovarla por otros tres.

Este mismo trabajo lo presentó en el concurso de ensayos en matemáticas que celebró Cambridge en 1936. El llamado premio Smith le fue otorgado al joven Turing, quien para ese entonces había penetrado los dominios de las matemáticas superiores al resolver de manera sorprendentemente sencilla, el problema de la decibilidad planteado por el legendario matemático alemán David Hilbert.

En términos llanos, la pregunta de Hilbert giraba en torno a si existe un método definido que pueda ser aplicado a cualquier aseveración, de manera que garantice el que se genere una decisión correcta sobre su veracidad. Aunque Hilbert intuitivamente creía que la respuesta a este problema era “sí”, Turing demostró sorpresivamente que realmente era “no”. Para contribuir su demostración usó un modelo teórico sumamente sencillo, que consistía en una máquina con una cinta de longitud infinita dividida en cuadros en cada uno de los cuales podría colocarse un solo símbolo. Las funciones de la máquina estaban limitadas a leer, escribir o borrar símbolos en la cinta, moviéndose para ello a razón de un cuadro a la vez (hacia la derecha o a la izquierda). A pesar de su sencillez, esta máquina realmente estaba modelando un algoritmo y constituía la primera herramienta teórica para explorar los límites de las aún inexistentes computadoras.

Las implicaciones de la demostración de Turing resultaron ser los orígenes de lo que hoy se conoce como teoría de la computación y gracias a este trabajo sabemos en la actualidad que sin importar qué tan rápidas y poderosas pueden llegar a ser las computadoras que el hombre construya, aún así seguirán existiendo problemas que nunca podremos resolver.

In [10]:
#Segmentación
oraciones_segmentadas = segmentar_oraciones_tokens(libro)
print(oraciones_segmentadas)

[['', 'el', 'matemático', 'inglés', 'alan', 'turing', 'fue', 'uno', 'de', 'los', 'pioneros', 'más', 'importantes', 'en', 'el', 'delineamiento', 'de', 'lo', 'que', 'más', 'tarde', 'se', 'convertiría', 'en', 'la', 'teoría', 'de', 'la', 'computación', '.', ''], ['', 'el', 'misterio', 'fue', 'un', 'común', 'denominador', 'a', 'lo', 'largo', 'de', 'su', 'vida', ',', 'entre', 'otras', 'cosas', 'por', 'su', 'participación', 'en', 'el', 'servicio', 'británico', 'de', 'inteligencia', 'durante', 'la', 'segunda', 'guerra', 'mundial', 'y', 'por', 'sus', 'mal', 'vistas', 'inclinaciones', 'sexuales', '.', ''], ['', 'su', 'vida', ',', 'llena', 'de', 'soledad', 'y', 'tropiezos', ',', 'fue', 'duramente', 'juzgada', 'al', 'exponer', 'públicamente', 'su', 'homosexualidad', 'en', 'los', 'años', 'cincuenta', ',', 'pero', 'ni', 'la', 'depresión', 'ni', 'el', 'cruel', 'repudio', 'de', 'la', 'sociedad', '-a', 'la', 'que', 'su', 'trabajo', 'contribuyó', 'a', 'liberar', 'del', 'yugo', 'alemán-', 'parecen', 'justificar', 'su', 'trágico', 'suicidio', ',', 'cometido', 'cuando', 'se', 'encontraba', 'en', 'el', 'clímax', 'de', 'su', 'productividad', 'científica', '.', ''], ['', 'sus', 'calificaciones', 'en', 'matemáticas', 'y', 'ciencias', 'eran', 'aceptables', ',', 'pero', 'los', 'maestros', 'se', 'quejaban', 'de', 'lo', 'sucio', 'de', 'su', 'trabajo', '.', ''], ['', 'su', 'madre', 'se', 'encontraba', 'sumamente', 'mortificada', 'porque', 'pensaba', 'que', 'alan', 'vería', 'truncadas', 'sus', 'aspiraciones', 'científicas', 'por', 'su', 'mal', 'desempeño', 'en', 'la', 'escuela', '.', ''], ['', 'con', 'esas', 'calificaciones', 'parecía', 'improbable', 'que', 'alan', 'pudiera', 'siquiera', 'aspirar', 'a', 'ingresar', 'a', 'la', 'universidad', '.', ''], ['', 'el', 'director', 'de', 'la', 'escuela', 'llegó', 'a', 'decir', 'si', 'alan', 'turing', 'deseaba', 'ser', 'científico', 'estaba', 'desperdiciando', 'su', 'tiempo', 'en', 'una', 'escuela', 'pública', '.', ''], ['', 'esas', 'palabras', 'fueron', 'casi', 'ciertas', ',', 'pues', 'turing', 'hubo', 'de', 'sufrir', 'mucho', 'durante', 'su', 'estancia', 'en', 'esa', 'institución', ',', 'en', 'la', 'que', 'los', 'anticuados', 'métodos', 'de', 'enseñanza', 'británicos', 'afortunadamente', 'no', 'lograron', 'apaciguar', 'su', 'curiosidad', 'por', 'la', 'ciencia', '.', ''], ['', 'si', 'su', 'madre', 'y', 'sus', 'profesores', 'hubieran', 'sabido', 'en', 'ese', 'entonces', 'que', 'este', 'joven', 'indisciplinado', 'estaba', 'destinado', 'a', 'convertirse', 'en', 'un', 'matemático', 'connotado', 'y', 'que', 'un', 'día', 'su', 'nombre', 'sería', 'pronunciado', 'con', 'respeto', 'por', 'los', 'teóricos', 'de', 'la', 'computación', 'más', 'importantes', 'del', 'mundo', ',', 'tal', 'vez', 'le', 'habrían', 'tenido', 'un', 'poco', 'más', 'de', 'paciencia', '.', ''], ['', 'alan', 'turing', 'fue', 'el', 'segundo', 'y', 'último', 'hijo', 'de', 'julius', 'turing', 'y', 'ethel', 'sara', 'stone', '.', ''], ['', 'el', 'inusual', 'apellido', 'turing', 'lo', 'colocaba', 'en', 'el', 'árbol', 'genealógico', 'de', 'una', 'familia', 'que', ',', 'aunque', 'no', 'era', 'rica', ',', 'pertenecía', 'a', 'la', 'clase', 'media', 'alta', 'inglesa', '.', ''], ['', 'su', 'padre', 'ingresó', 'al', 'servicio', 'civil', 'de', 'la', 'india', 'y', 'durante', 'su', 'estancia', 'en', 'ese', 'país', 'conoció', 'a', 'la', 'que', 'más', 'tarde', 'sería', 'su', 'esposa', '.', ''], ['', 'ethel', 'era', 'la', 'hija', 'del', 'ingeniero', 'en', 'jefe', 'de', 'los', 'ferrocarriles', 'de', 'madras', '(', 'en', 'la', 'india', ')', 'y', 'provenía', 'de', 'una', 'familia', 'anglo-irlandesa', 'de', 'un', 'estatus', 'socioeconómico', 'similar', 'al', 'de', 'julius', '.', ''], ['', 'aunque', 'fue', 'concebido', 'en', 'la', 'india', ',', 'probablemente', 'en', 'el', 'pueblo', 'de', 'chatrapur', ',', 'alan', 'turing', 'nació', 'en', 'warrington', 'lodge', ',', 'en', 'londres', ',', 'inglaterra', ',', 'el', '23', 'de', 'junio', 'de', '1912', '.', ''], ['', 'alan', 'turing', 'y', 'su', 'hermano', 'mayor', 'john', 'pasaron', 'una', 'infancia', 'alejados', 'de', 'sus', 'padres', ',', 'siempre', 'bajo', 'el', 'cuidado', 'de', 'terceras', 'personas', 'en', 'diversos', 'hogares', 'ingleses', ',', 'hasta', 'que', 'su', 'padre', 'se', 'retiró', 'del', 'servicio', 'en', '1926', '.', ''], ['', 'se', 'dice', 'que', 'la', 'inteligencia', 'de', 'alan', 'turing', 'se', 'manifestó', 'a', 'temprana', 'edad', ',', 'puues', 'a', 'los', '3', 'años', 'parecía', 'mostrar', 'una', 'inusual', 'capacidad', 'para', 'recordar', 'nuevas', 'palabras', '.', ''], ['', 'al', 'parecer', ',', 'su', 'gusto', 'por', 'la', 'educación', 'autodidacta', 'también', 'se', 'manifestó', 'en', 'su', 'niñez', 'porque', 'su', 'madre', 'cuenta', 'que', 'alan', 'estaba', 'aprendiendo', 'muy', 'lentamente', 'a', 'leer', ',', 'hasta', 'que', 'éste', 'encontró', 'un', 'libro', 'fácil', 'de', 'seguir', 'y', 'se', 'enseñó', 'a', 'sí', 'mismo', '.', ''], ['', 'asimismo', ',', 'su', 'inquietud', 'por', 'entender', 'los', 'fenómenos', 'de', 'la', 'naturaleza', 'lo', 'llevó', 'a', 'montar', 'un', 'laboratorio', 'rudimentario', 'de', 'química', 'en', 'el', 'sótano', 'de', 'su', 'casa', ',', 'cuando', 'contaba', 'con', 'solo', 'ocho', 'años', 'de', 'edad', '.', ''], ['', 'de', 'niño', ',', 'alan', 'quería', 'ser', 'médico', ',', 'por', 'lo', 'que', 'su', 'familia', 'veía', 'con', 'buenos', 'ojos', 'su', 'temprano', 'interés', 'en', 'la', 'química', '.', ''], ['', 'además', ',', 'buscando', 'que', 'el', 'pequeño', 'recibiera', 'una', 'buena', 'educación', 'básica', ',', 'sus', 'padres', 'lo', 'enviaron', 'en', 'el', 'verano', 'de', '1918', 'a', 'una', 'escuela', 'privada', 'para', 'niños', 'llamada', 'saint', 'michael', '’', 's', 'para', 'que', 'aprendiera', 'latín', '.', ''], ['', 'después', 'de', 'un', 'tiempo', 'su', 'mamá', 'lo', 'sacó', 'de', 'la', 'escuela', ',', 'porque', 'advirtió', 'que', 'alan', 'no', 'estaba', 'aprendiendo', 'mucho', ',', 'ya', 'que', 'llegó', 'a', 'los', 'nueve', 'años', 'de', 'edad', 'sin', 'saber', 'dividir', 'correctamente', 'y', 'sin', 'haber', 'alcanzado', 'un', 'nivel', 'aceptable', 'de', 'latín', '.', ''], ['', 'en', '1922', 'alan', 'ingresó', 'a', 'la', 'escuela', 'preparatoria', 'hazlehurst', ',', 'que', 'era', 'donde', 'estudiaba', 'su', 'hermano', '.', ''], ['', 'fue', 'en', 'hazlehurst', 'donde', 'alan', 'se', 'interesó', 'por', 'primera', 'vez', 'en', 'el', 'ajedrez', ',', 'y', 'fue', 'ahí', 'también', 'donde', 'su', 'interés', 'por', 'la', 'ciencia', '-sobre', 'todo', 'la', 'química', 'y', 'las', 'matemáticas-', 'fue', 'creciendo', 'cada', 'vez', 'más', ',', 'aunque', 'gran', 'parte', 'de', 'sus', 'estudios', 'tuvo', 'que', 'efectuarlos', 'de', 'manera', 'autodidacta', ',', 'debido', 'al', 'arcaico', 'sistema', 'de', 'enseñanza', 'que', 'reinaba', 'en', 'la', 'inglaterra', 'de', 'esos', 'días', '.', ''], ['', 'a', 'pesar', 'de', 'su', 'mal', 'desempeño', 'en', 'la', 'escuela', ',', 'alan', 'sorprendió', 'agradablemente', 'a', 'su', 'familia', 'cuando', 'aprobó', 'el', 'examen', 'común', 'de', 'admisión', 'a', 'escuelas', 'públicas', 'en', '1925', '.', ''], ['', 'sin', 'embargo', ',', 'como', 'su', 'madre', 'deseaba', 'enviar', 'a', 'alan', 'a', 'una', 'escuela', 'donde', 'pudiera', 'entender', 'su', 'extraña', 'manera', 'de', 'ser', 'y', 'su', 'extraordinario', 'sentido', 'de', 'independencia', ',', 'hubo', 'que', 'esperar', 'hasta', '1926', 'para', 'ingresar', 'a', 'la', 'escuela', 'sherborne', ',', 'cuando', 'contaba', 'con', '13', 'años', 'de', 'edad', '.', ''], ['', 'a', 'los', '14', 'años', 'ya', 'era', 'capaz', 'de', 'comprender', 'cuestiones', 'relativamente', 'avanzadas', 'de', 'cálculo', ',', 'pese', 'a', 'que', 'no', 'había', 'estudiado', 'el', 'tema', 'en', 'la', 'escuela', '.', ''], ['', 'asimismo', ',', 'se', 'dice', 'que', 'tenía', 'una', 'increíble', 'capacidad', 'para', 'realizar', 'cálculos', 'mentales', '.', ''], ['', 'fue', 'en', 'esta', 'época', 'también', 'en', 'la', 'que', 'empezó', 'a', 'desarrollar', 'una', 'afición', 'hacia', 'el', 'atletismo', 'que', 'le', 'acompañaría', 'toda', 'la', 'vida', '.', ''], ['', 'pese', 'a', 'su', 'mal', 'desempeño', 'en', 'materias', 'no', 'relacionadas', 'con', 'las', 'ciencias', '.', ''], ['', 'turing', 'logró', 'sobrevivir', 'en', 'sherborne', 'y', 'continuó', 'estudiando', 'matemáticas', 'por', 'su', 'cuenta', '.', ''], ['', 'en', '1928', 'se', 'interesó', 'en', 'la', 'teoría', 'general', 'de', 'la', 'relatividad', ',', 'de', 'albert', 'einstein', ',', 'y', 'aunque', 'se', 'dice', 'que', 'sus', 'notas', 'privadas', 'sobre', 'la', 'materia', 'bien', 'podrían', 'atribuirse', 'a', 'un', 'estudiante', 'de', 'posgrado', ',', 'casi', 'se', 'le', 'impidió', 'tomar', 'los', 'exámenes', 'para', 'obtener', 'el', 'certificado', 'de', 'educación', 'media', '.', ''], ['', 'durante', 'su', 'estancia', 'en', 'sherborne', ',', 'turing', 'desarrolló', 'el', 'hábito', 'de', 'no', 'prestar', 'atención', 'a', 'sus', 'clases', 'sino', 'hasta', 'el', 'final', 'del', 'semestre', ',', 'cuando', 'se', 'esmeraba', 'y', 'dejaba', 'asombrados', 'a', 'todos', 'al', 'obtener', 'calificaciones', 'suficientemente', 'buenas', 'para', 'aprobar', 'sus', 'cursos', '.', ''], ['', 'un', 'profesor', 'de', 'latín', ',', 'llegó', 'a', 'decirle', 'al', 'intrépido', 'alan', 'que', 'donaría', 'un', 'billón', 'de', 'libras', 'a', 'cualquier', 'institución', 'de', 'beneficencia', 'que', 'turing', 'eligiera', 'si', 'este', 'lograba', 'aprobar', 'su', 'curso', '.', ''], ['', 'a', 'pesar', 'del', 'mal', 'presagio', ',', 'alan', 'se', 'las', 'ingenió', 'para', 'aprobar', 'latín', ',', 'aunque', 'su', 'profesor', 'no', 'honró', 'la', 'apuesta', '.', ''], ['', 'fue', 'en', 'estos', 'días', 'cuando', 'turing', 'conoció', 'al', 'joven', 'christopher', 'morcom', ',', 'un', 'estudiante', 'muy', 'brillante', 'que', 'le', 'sirvió', 'de', 'compañero', 'intelectual', 'durante', 'una', 'época', 'de', 'intensa', 'curiosidad', 'científica', 'para', 'alan', '.', ''], ['', 'morcón', 'provenía', 'de', 'una', 'familia', 'rica', 'con', 'fuertes', 'bases', 'científicas', 'y', 'artísticas', '.', ''], ['', 'tras', 'conocerlo', ',', 'turing', 'se', 'sintió', 'inmediatamente', 'atraído', 'por', 'el', 'enorme', 'talento', 'y', 'las', 'sagaz', 'inteligencia', 'de', 'morcom', 'y', 'pronto', 'se', 'volvieron', 'muy', 'buenos', 'amigos', '.', ''], ['', 'incluso', 'a', 'veces', 'les', 'tocó', 'compartir', 'clases', ',', 'a', 'pesar', 'de', 'que', 'christopher', 'era', 'un', 'año', 'mayor', 'que', 'alan', '.', ''], ['', 'juntos', 'desarrollaron', 'experimentos', 'de', 'química', ',', 'resolvieron', 'problemas', 'de', 'matemáticas', ',', 'localizaron', 'estrellas', 'y', 'cometas', 'en', 'el', 'firmamento', 'y', 'conversaron', 'durante', 'interminables', 'horas', 'acerca', 'de', 'las', 'inagotables', 'ideas', 'y', 'preguntas', 'científicas', 'que', 'intrigaban', 'a', 'los', 'jóvenes', 'prospectos', '.', ''], ['', 'aunque', 'igualmente', 'brillante', 'que', 'alan', ',', 'christopher', 'se', 'distinguía', 'de', 'turing', 'por', 'ser', 'un', 'estudiante', 'modelo', 'que', 'sabía', 'obedecer', 'las', 'rígidas', 'reglas', 'que', 'regían', 'en', 'las', 'escuelas', 'inglesas', 'de', 'educación', 'media', 'de', 'la', 'época', '.', ''], ['', 'además', ',', 'poseía', 'aptitudes', 'que', 'estaban', 'mucho', 'más', 'allá', 'de', 'la', 'capacidad', 'de', 'turing', '.', ''], ['', 'tal', 'vez', 'por', 'ello', 'morcom', 'se', 'volvió', 'el', 'primer', 'héroe', 'de', 'la', 'adolescencia', 'de', 'turing', 'y', 'según', 'hodges', ',', 'su', 'primer', 'gran', 'amor', 'platónico', '.', ''], ['', 'en', '1929', 'morcom', 'presentó', 'los', 'exámenes', 'para', 'ingresar', 'al', 'prestigioso', 'trinity', 'college', 'de', 'la', 'universidad', 'de', 'cambridge', ',', 'y', 'obtuvo', 'una', 'beca', '-al', 'igual', 'que', 'lo', 'había', 'hecho', 'su', 'hermano', 'rupert', 'unos', 'años', 'antes', 'que', 'él-', '.', ''], ['', 'turing', 'tuvo', 'la', 'osadía', 'de', 'imitar', 'a', 'morcom', ',', 'a', 'pesar', 'de', 'contar', 'con', 'solo', '17', 'años', 'de', 'edad', 'y', ',', 'como', 'era', 'de', 'esperarse', ',', 'fracasó', 'en', 'su', 'intento', '.', ''], ['', 'lo', 'que', 'turing', 'lamentó', 'más', 'de', 'este', 'tropiezo', 'no', 'fue', 'tanto', 'el', 'no', 'haber', 'obtenido', 'la', 'beca', ',', 'sino', 'el', 'pensar', 'que', 'se', 'tendría', 'que', 'separar', 'de', 'christopher', 'durante', 'al', 'menos', 'un', 'año', '.', ''], ['', 'lo', 'que', 'alan', 'no', 'sabía', 'era', 'que', 'el', 'destino', 'estaba', 'a', 'punto', 'de', 'jugarle', 'una', 'mala', 'pasada', 'que', 'los', 'separaría', 'permanentemente', 'de', 'la', 'única', 'persona', 'que', 'realmente', 'comprendía', 'su', 'peculiar', 'interés', 'por', 'la', 'ciencia', '.', ''], ['', 'christopher', 'morcom', 'murió', 'el', '13', 'de', 'febrero', 'de', '1930', ',', 'después', 'de', '6', 'días', 'de', 'intenso', 'dolor', '.', ''], ['', 'aunque', 'turing', 'atribuyó', 'su', 'muerte', 'a', 'un', 'envenenamiento', 'envenenamiento', 'con', 'vanadio', ',', 'la', 'realidad', 'es', 'que', 'morcom', 'había', 'contraído', 'tuberculosis', 'bovina', 'en', 'la', 'infancia', 'por', 'beber', 'leche', 'de', 'vaca', 'infectada', 'y', 'eso', 'lo', 'había', 'hecho', 'ser', 'siempre', 'una', 'persona', 'muy', 'enfermiza', '.', ''], ['', 'su', 'mal', 'se', 'agudizó', 'tras', 'una', 'operación', 'que', 'se', 'efectuó', 'en', '1927', 'y', 'todos', 'los', 'esfuerzos', 'de', 'los', 'médicos', 'por', 'salvarlo', 'fueron', 'inútiles', '.', ''], ['', 'su', 'muerte', 'dejó', 'huella', 'profunda', 'en', 'turín', ',', 'quien', 'juró', 'completar', 'la', 'prometedora', 'carrera', 'científica', 'que', 'morcom', 'había', 'apenas', 'comenzado', '.', ''], ['', 'a', 'partir', 'de', 'ese', 'momento', 'alan', 'inició', 'una', 'correspondencia', 'frecuente', 'con', 'la', 'mamá', 'de', 'christopher', 'y', 'sus', 'intereses', 'se', 'tornaron', 'hacia', 'los', 'misterios', 'que', 'rodean', 'el', 'encapsulamiento', 'de', 'la', 'mente', 'en', 'la', 'materia', '.', ''], ['', 'con', 'el', 'firme', 'propósito', 'de', 'develar', 'los', 'secretos', 'de', 'la', 'muerte', 'con', 'ayuda', 'de', 'la', 'ciencia', ',', 'turing', 'comenzó', 'a', 'estudiar', 'física', 'cuántica', '.', ''], ['', 'en', 'su', 'segundo', 'intento', 'por', 'obtener', 'una', 'beca', 'en', 'cambridge', ',', 'turing', 'finalmente', 'logro', 'ser', 'aceptado', 'en', 'el', 'king', '’', 's', 'college', ',', 'que', 'fue', 'su', 'segunda', 'opción', 'en', 'el', 'examen', '.', ''], ['', 'esto', 'decepcionó', 'un', 'poco', 'alan', ',', 'que', 'lamentó', 'no', 'haber', 'podido', 'seguir', 'fielmente', 'los', 'pasos', 'de', 'christopher', ',', 'pero', 'fue', 'motivo', 'de', 'celebración', 'para', 'la', 'familia', 'turín', ',', 'que', 'pensó', 'que', 'después', 'de', 'todo', 'su', 'hijo', 'obtendría', 'la', 'buena', 'educación', 'que', 'todos', 'buscaban', '.', ''], ['', 'en', '1932', 'alan', 'comenzó', 'a', 'estudiar', 'el', 'entonces', 'reciente', 'trabajo', 'de', 'von', 'newman', 'en', 'mecánica', 'cuántica', ',', 'lo', 'cual', 'le', 'permitió', 'canalizar', 'sus', 'dudas', 'espirituales', 'por', 'la', 'vía', 'de', 'la', 'rigurosidad', 'científica', '.', ''], ['', 'al', 'mismo', 'tiempo', ',', 'el', 'ambiente', 'más', 'liberal', 'del', 'king', '’', 's', 'college', 'le', 'hizo', 'sentirse', 'mucho', 'más', 'relajado', 'que', 'en', 'sherborne', ',', 'y', 'la', 'homosexualidad', 'se', 'volvió', 'un', 'rasgo', 'distintivo', 'de', 'su', 'personalidad', '.', ''], ['', 'en', 'esa', 'época', 'hizo', 'amistad', 'con', 'un', 'joven', 'estudiante', 'de', 'matemáticas', 'llamado', 'james', 'atkins', ',', 'quien', 'se', 'volvería', 'más', 'tarde', 'su', 'amante', '.', ''], ['', 'pese', 'a', 'que', 'los', 'círculos', 'más', 'frecuentados', 'por', 'los', 'homosexuales', 'en', 'king', '’', 's', 'college', 'eran', 'los', 'literarios', ',', 'turing', 'prefería', 'los', 'deportes', 'y', 'era', 'frecuente', 'que', 'practicara', 'remo', ',', 'carreras', 'a', 'campo', 'traviesa', 'y', 'que', 'paseara', 'en', 'un', 'pequeño', 'velero', '.', ''], ['', 'también', 'aprendió', 'a', 'tocar', 'el', 'violín', ',', 'pero', 'nunca', 'se', 'volvió', 'diestro', 'con', 'el', 'instrumento', '.', ''], ['', 'tal', 'vez', 'debido', 'a', 'su', 'constante', 'oposición', 'a', 'los', 'sistemas', 'rígidos', 'como', 'los', 'que', 'había', 'experimentado', 'en', 'su', 'adolescencia', '.', ''], ['', 'turing', 'se', 'unió', 'al', 'movimiento', 'antibélico', 'que', 'pululaba', 'en', 'el', 'cambridge', 'de', 'los', 'años', 'treinta', '.', ''], ['', 'sus', 'ideas', 'de', 'esa', 'época', 'estaban', 'a', 'favor', 'de', 'la', 'izquierda', ',', 'aunque', 'nunca', 'llegó', 'a', 'participar', 'directamente', 'en', 'ningún', 'movimiento', 'político', 'importante', '.', ''], ['', 'las', 'cosas', 'empezaron', 'a', 'ir', 'bien', 'para', 'turing', ',', 'pues', 'se', 'graduó', 'de', 'la', 'licenciatura', 'en', 'matemáticas', 'con', 'honores', 'en', '1934', '.', ''], ['', 'su', 'redescubrimiento', 'del', 'teorema', 'del', 'límite', 'central', 'le', 'hizo', 'acreedor', 'a', 'una', 'beca', 'harold', 'fry', 'del', 'king', '’', 's', 'college', ',', 'que', 'le', 'permitía', 'ser', 'investigador', 'de', 'tiempo', 'completo', 'durante', 'tres', 'años', ',', 'con', 'posibilidad', 'de', 'renovarla', 'por', 'otros', 'tres', '.', ''], ['', 'este', 'mismo', 'trabajo', 'lo', 'presentó', 'en', 'el', 'concurso', 'de', 'ensayos', 'en', 'matemáticas', 'que', 'celebró', 'cambridge', 'en', '1936', '.', ''], ['', 'el', 'llamado', 'premio', 'smith', 'le', 'fue', 'otorgado', 'al', 'joven', 'turing', ',', 'quien', 'para', 'ese', 'entonces', 'había', 'penetrado', 'los', 'dominios', 'de', 'las', 'matemáticas', 'superiores', 'al', 'resolver', 'de', 'manera', 'sorprendentemente', 'sencilla', ',', 'el', 'problema', 'de', 'la', 'decibilidad', 'planteado', 'por', 'el', 'legendario', 'matemático', 'alemán', 'david', 'hilbert', '.', ''], ['', 'en', 'términos', 'llanos', ',', 'la', 'pregunta', 'de', 'hilbert', 'giraba', 'en', 'torno', 'a', 'si', 'existe', 'un', 'método', 'definido', 'que', 'pueda', 'ser', 'aplicado', 'a', 'cualquier', 'aseveración', ',', 'de', 'manera', 'que', 'garantice', 'el', 'que', 'se', 'genere', 'una', 'decisión', 'correcta', 'sobre', 'su', 'veracidad', '.', ''], ['', 'aunque', 'hilbert', 'intuitivamente', 'creía', 'que', 'la', 'respuesta', 'a', 'este', 'problema', 'era', '“', 'sí', '”', ',', 'turing', 'demostró', 'sorpresivamente', 'que', 'realmente', 'era', '“', 'no', '”', '.', ''], ['', 'para', 'contribuir', 'su', 'demostración', 'usó', 'un', 'modelo', 'teórico', 'sumamente', 'sencillo', ',', 'que', 'consistía', 'en', 'una', 'máquina', 'con', 'una', 'cinta', 'de', 'longitud', 'infinita', 'dividida', 'en', 'cuadros', 'en', 'cada', 'uno', 'de', 'los', 'cuales', 'podría', 'colocarse', 'un', 'solo', 'símbolo', '.', ''], ['', 'las', 'funciones', 'de', 'la', 'máquina', 'estaban', 'limitadas', 'a', 'leer', ',', 'escribir', 'o', 'borrar', 'símbolos', 'en', 'la', 'cinta', ',', 'moviéndose', 'para', 'ello', 'a', 'razón', 'de', 'un', 'cuadro', 'a', 'la', 'vez', '(', 'hacia', 'la', 'derecha', 'o', 'a', 'la', 'izquierda', ')', '.', ''], ['', 'a', 'pesar', 'de', 'su', 'sencillez', ',', 'esta', 'máquina', 'realmente', 'estaba', 'modelando', 'un', 'algoritmo', 'y', 'constituía', 'la', 'primera', 'herramienta', 'teórica', 'para', 'explorar', 'los', 'límites', 'de', 'las', 'aún', 'inexistentes', 'computadoras', '.', ''], ['', 'las', 'implicaciones', 'de', 'la', 'demostración', 'de', 'turing', 'resultaron', 'ser', 'los', 'orígenes', 'de', 'lo', 'que', 'hoy', 'se', 'conoce', 'como', 'teoría', 'de', 'la', 'computación', 'y', 'gracias', 'a', 'este', 'trabajo', 'sabemos', 'en', 'la', 'actualidad', 'que', 'sin', 'importar', 'qué', 'tan', 'rápidas', 'y', 'poderosas', 'pueden', 'llegar', 'a', 'ser', 'las', 'computadoras', 'que', 'el', 'hombre', 'construya', ',', 'aún', 'así', 'seguirán', 'existiendo', 'problemas', 'que', 'nunca', 'podremos', 'resolver'

## Vectorizar

In [11]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
vectorizer = TfidfVectorizer(tokenizer=lambda x: x, preprocessor=lambda x: x)
X = vectorizer.fit_transform(oraciones_segmentadas)
vocabulario = vectorizer.get_feature_names_out()
print(X.shape)

indices_filas = [f"{i}" for i in range(len(oraciones_segmentadas))]
tabla_tfidf = pd.DataFrame(X.toarray(), index=indices_filas, columns=vocabulario)
tabla_tfidf

#Las veces que aprece la palabra

(72, 823)

/usr/local/lib/python3.13/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,,(,),",",-a,-al,-sobre,.,13,14,...,yugo,árbol,él-,época,éste,último,única,’,“,”
0,0.116456,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.058228,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,0.092790,0.000000,0.000000,0.058695,0.000000,0.0,0.0,0.046395,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,0.067050,0.000000,0.000000,0.169651,0.154125,0.0,0.0,0.033525,0.0,0.0,...,0.154125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,0.136785,0.000000,0.000000,0.086524,0.000000,0.0,0.0,0.068392,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
4,0.123250,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.061625,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.096760,0.000000,0.000000,0.061206,0.000000,0.0,0.0,0.048380,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444834,0.444834
68,0.089352,0.000000,0.000000,0.056520,0.000000,0.0,0.0,0.044676,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
69,0.084116,0.176301,0.176301,0.106416,0.000000,0.0,0.0,0.042058,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
70,0.105285,0.000000,0.000000,0.066598,0.000000,0.0,0.0,0.052642,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
71,0.069581,0.000000,0.000000,0.044014,0.000000,0.0,0.0,0.034791,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

## Metrica para cada oración

Mide la importancia media de las palabras de cada oración sin beneficiar a las oraciones largas.

In [23]:
metrica=tabla_tfidf.mean(axis=1)
metrica

0     0.005583
1     0.006782
2     0.008014
3     0.005152
4     0.005449
        ...
67    0.004982
68    0.006651
69    0.006188
70    0.006113
71    0.008159
Length: 72, dtype: float64

## Ordenar las oraciones de mayor a menor

In [24]:
tabla_tfidf['Promedio_TFIDF'] =metrica
tabla_ordenada = tabla_tfidf.sort_values(by='Promedio_TFIDF', ascending=False)
tabla_ordenada

,,(,),",",-a,-al,-sobre,.,13,14,...,árbol,él-,época,éste,último,única,’,“,”,Promedio_TFIDF
22,0.067260,0.0,0.0,0.127637,0.000000,0.0,0.154608,0.033630,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008160
71,0.069581,0.0,0.0,0.044014,0.000000,0.0,0.000000,0.034791,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008159
8,0.074542,0.0,0.0,0.047152,0.000000,0.0,0.000000,0.037271,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008029
2,0.067050,0.0,0.0,0.169651,0.154125,0.0,0.000000,0.033525,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008014
30,0.079979,0.0,0.0,0.151774,0.000000,0.0,0.000000,0.039990,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.007517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,0.149939,0.0,0.0,0.094845,0.000000,0.0,0.000000,0.074970,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004326
40,0.160983,0.0,0.0,0.101830,0.000000,0.0,0.000000,0.080491,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004300
35,0.154596,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.077298,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004213
28,0.171972,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.085986,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004196
29,0.164345,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.082172,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004154

In [25]:
#Porcentaje de texto
porcentaje=int(input("¿Qué porcentaje de texto que deseas reducir? "))
numero_oraciones=int(porcentaje*len(oraciones_segmentadas)/100)
numero_oraciones

¿Qué porcentaje de texto que deseas reducir? 30

21

In [42]:
#Armar el resumen
oraciones_seleccionadas=sorted([int(i) for i in tabla_ordenada[:numero_oraciones].index])
print(oraciones_seleccionadas)

[1, 2, 7, 8, 14, 16, 19, 20, 22, 24, 30, 31, 38, 42, 47, 53, 57, 65, 66, 68, 71]

In [50]:
resumen = " \n".join(
    [" ".join(oraciones_segmentadas[i]) for i in oraciones_seleccionadas]
)
print(resumen)

 el misterio fue un común denominador a lo largo de su vida , entre otras cosas por su participación en el servicio británico de inteligencia durante la segunda guerra mundial y por sus mal vistas inclinaciones sexuales .
 su vida , llena de soledad y tropiezos , fue duramente juzgada al exponer públicamente su homosexualidad en los años cincuenta , pero ni la depresión ni el cruel repudio de la sociedad -a la que su trabajo contribuyó a liberar del yugo alemán- parecen justificar su trágico suicidio , cometido cuando se encontraba en el clímax de su productividad científica .
 esas palabras fueron casi ciertas , pues turing hubo de sufrir mucho durante su estancia en esa institución , en la que los anticuados métodos de enseñanza británicos afortunadamente no lograron apaciguar su curiosidad por la ciencia .
 si su madre y sus profesores hubieran sabido en ese entonces que este joven indisciplinado estaba destinado a convertirse en un matemático connotado y que un día su nombre sería pronunciado con respeto por los teóricos de la computación más importantes del mundo , tal vez le habrían tenido un poco más de paciencia .
 alan turing y su hermano mayor john pasaron una infancia alejados de sus padres , siempre bajo el cuidado de terceras personas en diversos hogares ingleses , hasta que su padre se retiró del servicio en 1926 .
 al parecer , su gusto por la educación autodidacta también se manifestó en su niñez porque su madre cuenta que alan estaba aprendiendo muy lentamente a leer , hasta que éste encontró un libro fácil de seguir y se enseñó a sí mismo .
 además , buscando que el pequeño recibiera una buena educación básica , sus padres lo enviaron en el verano de 1918 a una escuela privada para niños llamada saint michael ’ s para que aprendiera latín .
 después de un tiempo su mamá lo sacó de la escuela , porque advirtió que alan no estaba aprendiendo mucho , ya que llegó a los nueve años de edad sin saber dividir correctamente y sin haber alcanzado un nivel aceptable de latín .
 fue en hazlehurst donde alan se interesó por primera vez en el ajedrez , y fue ahí también donde su interés por la ciencia -sobre todo la química y las matemáticas- fue creciendo cada vez más , aunque gran parte de sus estudios tuvo que efectuarlos de manera autodidacta , debido al arcaico sistema de enseñanza que reinaba en la inglaterra de esos días .
 sin embargo , como su madre deseaba enviar a alan a una escuela donde pudiera entender su extraña manera de ser y su extraordinario sentido de independencia , hubo que esperar hasta 1926 para ingresar a la escuela sherborne , cuando contaba con 13 años de edad .
 en 1928 se interesó en la teoría general de la relatividad , de albert einstein , y aunque se dice que sus notas privadas sobre la materia bien podrían atribuirse a un estudiante de posgrado , casi se le impidió tomar los exámenes para obtener el certificado de educación media .
 durante su estancia en sherborne , turing desarrolló el hábito de no prestar atención a sus clases sino hasta el final del semestre , cuando se esmeraba y dejaba asombrados a todos al obtener calificaciones suficientemente buenas para aprobar sus cursos .
 juntos desarrollaron experimentos de química , resolvieron problemas de matemáticas , localizaron estrellas y cometas en el firmamento y conversaron durante interminables horas acerca de las inagotables ideas y preguntas científicas que intrigaban a los jóvenes prospectos .
 en 1929 morcom presentó los exámenes para ingresar al prestigioso trinity college de la universidad de cambridge , y obtuvo una beca -al igual que lo había hecho su hermano rupert unos años antes que él- .
 aunque turing atribuyó su muerte a un envenenamiento envenenamiento con vanadio , la realidad es que morcom había contraído tuberculosis bovina en la infancia por beber leche de vaca infectada y eso lo había hecho ser siempre una persona muy enfermiza .
 esto decepcionó un poco alan , que lamentó no haber podido seguir fielmente los pasos de christopher , pero fue motivo de celebración para la familia turín , que pensó que después de todo su hijo obtendría la buena educación que todos buscaban .
 pese a que los círculos más frecuentados por los homosexuales en king ’ s college eran los literarios , turing prefería los deportes y era frecuente que practicara remo , carreras a campo traviesa y que paseara en un pequeño velero .
 el llamado premio smith le fue otorgado al joven turing , quien para ese entonces había penetrado los dominios de las matemáticas superiores al resolver de manera sorprendentemente sencilla , el problema de la decibilidad planteado por el legendario matemático alemán david hilbert .
 en términos llanos , la pregunta de hilbert giraba en torno a si existe un método definido que pueda ser aplicado a cualquier aseveración , de manera que garantice el que se genere una decisión correcta sobre su veracidad .
 para contribuir su demostración usó un modelo teórico sumamente sencillo , que consistía en una máquina con una cinta de longitud infinita dividida en cuadros en cada uno de los cuales podría colocarse un solo símbolo .
 las implicaciones de la demostración de turing resultaron ser los orígenes de lo que hoy se conoce como teoría de la computación y gracias a este trabajo sabemos en la actualidad que sin importar qué tan rápidas y poderosas pueden llegar a ser las computadoras que el hombre construya , aún así seguirán existiendo problemas que nunca podremos resolver .